api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'
urlpatterns = [
    url(r'^(?P<dataset_id>[0-9]+)/(?P<field_name>[\w\-]+)$', views.get_field, name='get_field'),
]

build_model/urls.py
from django.conf.urls import url

from . import views

app_name = 'build_model'
urlpatterns = [
    url(r'^$', views.all, name='all'),
    url(r'^(?P<model_id>[0-9]+)/info$', views.info, name='info'),
    url(r'^(?P<dataset_id>[0-9]+)$', views.build, name="build"),
    url(r'^(?P<model_id>[0-9]+)/delete_model',
        views.delete_model, name='delete_model'),
    url(r'^(?P<model_id>[0-9]+)/test$', views.test, name='test'),
    url(r'^results/$', views.results, name='results'),
]

dataset/urls.py
from django.conf.urls import url

from . import views

app_name = 'dataset'
urlpatterns = [
    url(r'^$', views.upload, name='upload'),
    url(r'^(?P<dataset_id>[0-9]+)/delete_dataset', views.delete_dataset, name='delete_dataset'),
    url(r'^(?P<dataset_id>[0-9]+)/edit$', views.edit, name='edit'),
    url(r'^(?P<dataset_id>[0-9]+)/(?P<field_name>[\w\-]+)$', views.edit_field, name='edit_field'),
    url(r'^hide_field/$', views.hide_field, name='hide_field'),
]

dataset/models.py
import json
import pandas as pd
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from storages.backends.dropbox import DropBoxStorage
from django.conf import settings
from dropbox.files import WriteMode
from .validators import validate_file_extension, validate_file_size
from .preprocessing import *
from .settings import *


class Dataset(models.Model):
    name = models.CharField(max_length=30)
    row_count = models.IntegerField(default=0)
    num_fields = models.IntegerField(default=0)
    file = models.FileField(upload_to=CSV_DIR, validators=[
                            validate_file_extension, validate_file_size])
    status = models.CharField(max_length=30, default="disable")
    label_encode = models.BinaryField()
    description = models.TextField(default='')
    cleaned = models.BooleanField(default=False)
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)

    def __str__(self):
        return self.file.name

    # метод возвращает y для dataset
    def get_y_name(self):
        return Field.objects.get(data_file=self, is_y=True).name

    # метод возвращает массив с именами x
    def get_x_names(self):
        names = []
        for field in Field.objects.filter(data_file=self, is_y=False):
            names.append(field.name)
        return names

    def update_file(self, data_frame):
        if isinstance(self.file.storage, DropBoxStorage):
            dbx = DropBoxStorage(settings.DROPBOX_OAUTH2_TOKEN)
            mode = WriteMode.overwrite
            name = self.file.file.name
            data = data_frame.to_csv(index=False)
            dbx.client.files_upload(bytes(data, 'utf-8'), name, mode)
        else:
            data_frame.to_csv(self.file.url, index=False)

@receiver(post_save, sender=Dataset)
def clean_data(instance, created, **kwargs):
    ''' очистка данных '''
    if created:
        data_frame = pd.read_csv(instance.file.url)
        drop_strings(data_frame)
        data_frame = drop_na(data_frame)
        instance.update_file(data_frame)
        instance.cleaned = True
        instance.save()


@receiver(post_save, sender=Dataset)
def add_name(instance, created, **kwargs):
    ''' добавление имени '''
    if created:
            data_frame = pd.read_csv(instance.file.url)
            instance.name = 'file' + str(instance.id)
            instance.row_count, instance.num_fields = data_frame.shape
            instance.save()


@receiver(post_save, sender=Dataset)
def add_description(instance, created, **kwargs):
    ''' добавление описания '''
    if created:
        data = pd.read_csv(instance.file.url)
        field_desc = {}
        for name in data.columns:
            field_desc[name] = {}

            # get statistic
            statistic = data[name].describe(percentiles=[]).to_json()
            field_desc[name]["statistic"] = json.loads(statistic)
            uniq_fields = list(data[name].unique())
            val_counts = data[name].value_counts().to_dict()
            field_desc[name]["active"] = "yes"
            if str(data[name].dtype) == 'object':
                field_desc[name]["type"] = "select"
                field_desc[name]["choices"] = uniq_fields
                field_desc[name]["history"] = list(val_counts.keys())
                field_desc[name]["values"] = list(val_counts.values())
            else:
                field_desc[name]["type"] = "number"
            if len(uniq_fields) == 2:
                field_desc[name]["dtype"] = "boolean"
            elif len(uniq_fields) > 2:
                field_desc[name]["dtype"] = "order"
        try:
            instance.description = json.dumps(field_desc, separators=(',', ':'))
        except Exception as e:
            print(field_desc)
            raise e
        instance.save()


class Field(models.Model):
    data_file = models.ForeignKey(Dataset, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    is_y = models.BooleanField(default=False)
    field_type = models.CharField(max_length=200)

    def __str__(self):
        return self.name

dataset/forms.py
from django import forms
from .models import Dataset


class UploadFileForm(forms.ModelForm):
    class Meta:
        model = Dataset
        fields = ('file',)

dataset/views.py
import pandas as pd
import json
import logging
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .settings import *
from .files import get_size
from .models import Dataset, Field
from .forms import UploadFileForm
from storages.backends.dropbox import DropBoxStorage


logger = logging.getLogger(__name__)


# Представление, загружающее dataset на диск.
@login_required
def upload(request, **kwargs):
    if request.user.is_superuser:
        datasets = Dataset.objects.all()
    else:
        datasets = Dataset.objects.filter(user=request.user)

    if request.method == 'GET':
        form = UploadFileForm()
        return render(
            request,
            'dataset/upload.html', {
                'form': form,
                'dataset': datasets}, )

    elif request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if not request.user.is_superuser:
            if Dataset.objects.filter(user=request.user).exists():
                data = {'is_valid': False, 'error': "You alredy have dataset"}
                return JsonResponse(data)
        if form.is_valid():
            try:
                form_field = form.save(commit=False)
                # check if another file exist for non superuser
                form_field.user = request.user
                form_field.save()
                data = {'is_valid': True, 'name': form_field.file.name, 'url': form_field.file.url, 'id': form_field.id}
            except Exception as e:
                # Dataset.objects.last().delete()
                data = {'is_valid': False, 'error': str(e)}
            return JsonResponse(data)
        else:
            data = {'is_valid': False, 'error': form.errors}
            return JsonResponse(data)


# Представление с выбором целевой переменной и статистикой.
@login_required
def edit(request, dataset_id):
    try:
        if not request.user.is_superuser:
            dataset = Dataset.objects.get(pk=dataset_id, user=request.user)
        else:
            dataset = Dataset.objects.get(pk=dataset_id)
    except Exception:
        return HttpResponseRedirect(reverse('dataset:upload'))

    # Use "nrows = 0" in read_csv method to read 0 rows
    # if isinstance(dataset.file.storage, DropBoxStorage)
    data_frame = pd.read_csv(dataset.file.url, nrows=0)
    for name in data_frame.columns:
        if not Field.objects.filter(data_file=dataset, name=name).exists():
            Field(data_file=dataset, name=name, field_type=str(data_frame[name].dtype)).save()

    fields = Field.objects.filter(data_file_id=dataset_id)
    description = json.loads(dataset.description)

    bool_fields = []
    for name in description.keys():
        if description[name]["dtype"] == "boolean":
            bool_fields.append(name)

    if request.method == 'GET':
        return render(
            request,
            'dataset/edit.html', {
                'fields': fields,
                'bool_fields': bool_fields,
                'dataset': dataset})

    elif request.method == 'POST':
        Dataset.objects.filter(
            pk=dataset_id).update(name=request.POST['file_name'])
        for field in fields:
            if field.name == request.POST['choice']:
                Field.objects.filter(
                    data_file=dataset,
                    name=field.name).update(is_y=True)
            else:
                Field.objects.filter(
                    data_file=dataset,
                    name=field.name).update(is_y=False)
        return HttpResponseRedirect(reverse('dataset:upload'))


@login_required
def edit_field(request, dataset_id, field_name):
    # read data file from disc
    try:
        if not request.user.is_superuser:
            dataset = Dataset.objects.get(pk=dataset_id, user=request.user)
        else:
            dataset = Dataset.objects.get(pk=dataset_id)
    except Exception:
        return HttpResponseRedirect(reverse('dataset:upload'))

    # get field from db
    field = get_object_or_404(Field, name=field_name, data_file_id=dataset_id)

    # get description
    desc = json.loads(dataset.description)

    if request.method == 'GET':
        return render(
            request,
            'dataset/edit_field.html', {
                'field': field,
                'desc': desc[field_name],
                'dataset_id': dataset_id})

    elif request.method == 'POST':
        # change name in dataset_field table
        field.name = request.POST.get('field_name')
        field.save(force_update=True)

        # change name in csv file
        data_frame = pd.read_csv(dataset.file.url)
        data_frame.columns = data_frame.columns.str.replace(
            field_name,
            request.POST.get('field_name'))

        dataset.update_file(data_frame)
        # change name in description file
        desc[field_name]["help_text"] = request.POST.get("help_text")
        if request.POST.get("max_value"):
            desc[field_name]["max_value"] = request.POST.get("max_value")
        if request.POST.get("min_value"):
            desc[field_name]["min_value"] = request.POST.get("min_value")
        desc[request.POST.get('field_name')] = desc.pop(field_name)

        # change description in dataset_dataset table
        dataset.description = json.dumps(desc, separators=(',', ':'))
        dataset.save()

        return HttpResponseRedirect(
            reverse(
                'dataset:edit',
                args=[dataset_id]))


# Delete dataset
@login_required
def delete_dataset(request, dataset_id):
    try:
        if not request.user.is_superuser:
            dataset = Dataset.objects.get(pk=dataset_id, user=request.user)
        else:
            dataset = Dataset.objects.get(pk=dataset_id)
    except Exception:
        return HttpResponseRedirect(reverse('dataset:upload'))

    dataset.file.delete()
    dataset.delete()
    for field in Field.objects.filter(data_file_id=dataset_id):
        field.delete()
    return HttpResponseRedirect(reverse('dataset:upload'))


# Hide field
@login_required
def hide_field(request):
    try:
        if not request.user.is_superuser:
            dataset = Dataset.objects.get(pk=request.GET.get('dataset_id'), user=request.user)
        else:
            dataset = Dataset.objects.get(pk=request.GET.get('dataset_id'))
    except Exception:
        return HttpResponse("Error {}".format(dataset_id))

    desc = json.loads(dataset.description)
    if desc[request.GET.get('field_id')]["active"] == "yes":
        desc[request.GET.get('field_id')]["active"] = "no"
    else:
        desc[request.GET.get('field_id')]["active"] = "yes"
    return HttpResponse("OK")

dataset/templates/dataset/edit.html
{% extends "base.html" %}
{% load dict_key_access %}

{% block content %}
<h2>Edit dataset</h2>
<br>

<form class="form-inline" role="form" enctype="multipart/form-data" method="post">
	{% csrf_token %}
	<div class="form-group">
		<input type="text" class="form-control" id="nameEdit" name="file_name" value="{{dataset.name}}">
	</div>
	<div class="divider"></div>
	<div class="form-group">
		<select class="form-control" name="choice">
			{% for field in bool_fields %}
			<option value="{{field}}">{{field}}</option>
			{% endfor %}
		</select>
	</div>
	<input type="hidden" name="active" value="active">
	<div class="divider"></div>
	<button type="submit" class="btn btn-default btn-primary">Save</button>
</form>
<br>

<h4>Fields</h4>
<div class="table-responsive">
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>name</th>
				<th>type</th>
				<th>delete</th>
			</tr>
		</thead>
		<tbody>
	    </tr>
	    {% for field in fields %}
		    <tr>
		        <td> <a href="{% url 'dataset:edit_field' dataset_id=dataset.id field_name=field.name %}">{{ field.name }}</a> </td>
		        <td>{{field.field_type}}</td>
		        <td><a href="{% url 'dataset:hide_field' %}?field_id={{field.id}}&dataset_id={{dataset.id}}"><i class="fa fa-fw fa-trash"></i> Delete</a></td>
		    </tr>
		{% endfor %}
	  </tbody>
	</table>
</div>
{% endblock content%}

dataset/templates/dataset/edit_field.html
{% extends "base.html" %}
{% load dict_key_access %}
{% load static %}

{% block content %}
<h2>Edit Field</h2>
<br>

<form class="form" role="form" enctype="multipart/form-data" method="post" id="fieldForm">
	{% csrf_token %}
	  <div class="row">
    	<div class="col">
    		<label for="nameEdit">Name</label>
    		<input type="text" class="form-control" id="nameEdit" name="field_name" value="{{field.name}}">
		</div>
		<div class="col"></div>
	</div>
	<br>
	<div class="row">
    	<div class="col">
			<div class="form-group">
		    	<label for="help_text">Description</label>
		    	<textarea class="form-control" id="help_text" rows="3" name="help_text" >{{desc.help_text}}</textarea>
		  	</div>
		</div>
		<div class="col"></div>
	</div>
	{% if desc.type == 'number'%}
	<br>
	<div class="row">
		<div class="col">
			<label for="minValue">Min</label>
    		<input type="number" class="form-control" id="minValue" name="min_value" value="{{field.min_value}}">
		</div>
		<div class="col">
			<label for="maxValue">Max</label>
    		<input type="number" class="form-control" id="maxValue" name="max_value" value="{{field.max_value}}">
		</div>
		<div class="col"></div>
	</div>
	{% endif %}
	<br>
	<button type="submit" class="btn btn-default btn-primary">Save</button>
</form>
<br>

<div class='row'>
	<div class='col-sm-6' id="chartContainer">
	</div>
</div>

<h4>Statistic</h4>	
<div class="table-responsive">
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>parameter</th>
				<th>value</th>
			</tr>
		</thead>
		<tbody>
	    </tr>
	    {% for field in desc.statistic %}
		    <tr>
		        <td>{{field}}</td>
		        <td>{{desc.statistic|get_item:field}}</td>
		    </tr>
		{% endfor %}
		{% if desc.type == "select" %}
		<tr>
			<td>choices</td>
			<td>{{desc.choices}}</td>
		</tr>
	  	{% endif %}
	  </tbody>
	</table>
</div>
{% endblock content%}
{% block javascript %}
{{ block.super }}
<script src="{% static "js/graph.js" %}"></script>
{% endblock %}

dataset/templates/dataset/upload.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h2>Upload dataset</h2>
<br>
{% if not user.is_superuser %}
<div class="alert alert-info" role="alert">
  <strong> You can upload only one file not larger than 5 megabytes </strong>
</div>
{% endif %}
<div id = "alert_placeholder"></div>

<div class="fade" id="modal-progress" data-backdrop="false" data-keyboard="false">
	<div class="progress">
  		<div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>
	</div>
</div>

<div class="divider"></div>

{% if dataset %}
<div class="table-responsive">
	<table id="file-table" class="table table-bordered">
		<tr>
		<th>Name</th>
		<th>Rows</th> 
		<th>Fields</th>
		<th></th>
		</tr>
		{% for name in dataset %}
		<tr>
			<td><a href="{% url 'dataset:edit' name.id %}">{{name.name}}</a></td>
			<td>{{name.row_count}}</td>
			<td>{{name.num_fields}}</td>
			<td>
				<a href="{% url 'build_model:build' name.id%}"><i class="fa fa-fw fa-wrench"></i> Build</a>
				<a href="{% url 'dataset:delete_dataset' name.id %}"><i class="fa fa-fw fa-trash"></i> Delete</a>
			</td>
		</tr>
		{% endfor %}
	</table>
</div>
{% endif %}

<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<div class="row">
		<div class="col">
			<div style="margin-bottom: 20px;">
    			<button type="button" class="btn btn-primary js-upload-photos">
      				<span class="glyphicon glyphicon-cloud-upload"></span> Upload file
    			</button>
			    <input id="fileupload" type="file" name="file"
			           style="display: none;"
			           data-url="{% url 'dataset:upload' %}"
			           data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
			</div>
		</div>
	</div>
</form>
{% endblock content %}
{% block javascript %}
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  {# JQUERY FILE UPLOAD SCRIPTS #}
  <script src="{% static 'js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.fileupload.js' %}"></script>

  {# PHOTOS PAGE SCRIPTS #}
  <script src="{% static 'js/progress-bar-upload.js' %}"></script>
{% endblock %}