api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'
urlpatterns = [
    url(r'^(?P<dataset_id>[0-9]+)/(?P<field_name>[\w\-]+)$', views.get_field, name='get_field'),
]

dataset/urls.py
from django.conf.urls import url

from . import views

app_name = 'dataset'
urlpatterns = [
    url(r'^$', views.upload, name='upload'),
    url(r'^(?P<dataset_id>[0-9]+)/delete_dataset', views.delete_dataset, name='delete_dataset'),
    url(r'^(?P<dataset_id>[0-9]+)/edit$', views.edit, name='edit'),
    url(r'^(?P<dataset_id>[0-9]+)/(?P<field_name>[\w\-]+)$', views.edit_field, name='edit_field'),
    url(r'^hide_field/$', views.hide_field, name='hide_field'),
]

profiles/urls.py
from django.conf.urls import url

from . import views

app_name = 'profiles'
urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^delete_account/$', views.delete_account, name='delete_account'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^info/$', views.user_profile, name='user_profile'),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    try:
        instance.profile.save()
    except AttributeError:
        profile = Profile.objects.create(user=instance)
        profile.save()

profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        max_length=254,
        help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

profiles/views.py
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from .forms import SignUpForm
from .tokens import account_activation_token

from django.contrib.auth.models import User
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth import login, logout, authenticate

from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth.decorators import login_required

import os

from django.contrib.auth.forms import AuthenticationForm


@login_required
def user_profile(request):
    user = User.objects.get(id=request.user.id)
    if request.method == 'GET':
        return render(
            request,
            'profiles/user_profile.html',
            {'user': user, }, )
    elif request.method == 'POST':
        user.username  = request.POST['userName']
        user.email = request.POST['userEmail']
        user.save()
        return HttpResponseRedirect(reverse('profiles:user_profile'))


@login_required
def delete_account(request):
    user = User.objects.get(id=request.user.id)
    user.delete()
    return HttpResponseRedirect(reverse('profiles:signup'))

@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('profiles:signin'))


def account_activation_sent(request):
    return render(request, 'profiles/account_activation_sent.html')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        #login(request, user)
        return HttpResponseRedirect(reverse('profiles:signin'))
    else:
        return render(request, 'account_activation_invalid.html')


def signup(request):
    if request.method == 'POST':
        if request.user.is_active:
            logout(request)
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate Your MySite Account'
            message = render_to_string('profiles/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': force_text(urlsafe_base64_encode(force_bytes(user.pk))),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)

            dir = os.path.dirname(__file__)
            log_file = os.path.join(dir, '../logs/tokens.log')
            with open(log_file, 'a') as the_file:
                the_file.write(message)

            return HttpResponseRedirect(reverse('profiles:account_activation_sent'))
    else:
        form = SignUpForm()
    return render(request, 'profiles/register.html', {'form': form})


def signin(request):
    if request.method == 'GET':
        if request.user.is_active:
            return HttpResponseRedirect(reverse('dataset:upload'))
        else:
            form = AuthenticationForm()
            return render(request,'profiles/signin.html', {'form': form} )
    elif request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('dataset:upload'))
        else:
            form.add_error(None, "Wrong")
            return render(request,'profiles/signin.html', {'form': form} )

profiles/templates/profiles/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'profiles:activate' uidb64=uid token=token %}
{% endautoescape %}

profiles/templates/profiles/account_activation_invalid.html
{% extends "base.html" %}

{% block navigation %}
{% endblock %}

{% block main %}
<div class="card card-register mx-auto mt-5">
	<div class="card-body">
		<p> invalid registration token</p>
	</div>
</div>	
{% endblock%}

profiles/templates/profiles/account_activation_sent.html
{% extends "base.html" %}

{% block navigation %}
{% endblock %}

{% block main %}
<div class="card card-register mx-auto mt-5">
	<div class="card-body">
		<p> Please confirm your email address to complete the registration</p>
	</div>
</div>	
{% endblock%}

profiles/templates/profiles/register.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block navigation %}
{% endblock %}

{% block main %}
<body class="bg-dark">
  <div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Register</div>
        <div class="card-body">
        <form method="post">
          {% csrf_token %}
            {{ form|crispy }}
            <button type="submit">Sign up</button>
        </form>
        <div class="text-center">
          <a class="d-block small mt-3" href="{% url 'profiles:signin' %}">Login Page</a>
          <a class="d-block small" href="">Forgot Password?</a>
        </div>
      </div>
    </div>
  </div>
</body>
{% endblock %}

profiles/templates/profiles/signin.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block navigation %}
{% endblock %}

{% block main %}

<body class="bg-dark">
  <div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Login</div>
      <div class="card-body">
        <form method="post" action="{% url 'profiles:signin' %}">
        {% csrf_token %}
          {{form|crispy}}
          <div>
            <input type="submit" value="login" />
            <input type="hidden" name="next" value="{{ next }}" />
          </div>
        </form>

        <div class="text-center">
          <a class="d-block small mt-3" href="{% url 'profiles:signup' %}">Register an Account</a>
          <a class="d-block small" href="">Forgot Password?</a>
        </div>
      </div>
    </div>
  </div>
</body>

{% endblock %}

profiles/templates/profiles/user_profile.html
{% extends "base.html" %}

{% block content %}
<center><h2>User</h2></center>
<div class="card card-register mx-auto mt-5">
	<div class="card-body">
		<form class="form" role="form" enctype="multipart/form-data" method="post">
			{% csrf_token %}
			<label for="userName">User name</label>		
			<input type="text" class="form-control" name="userName" value="{{user.username}}" readonly>
			<br>
			<label for="userEmail">Email</label>		
			<input type="email" class="form-control" name="userEmail" value="{{user.email}}" readonly>
			<br>
			<label for="accountType">Account type</label>
			{% if user.is_superuser %}
			<input class="form-control" type="text" placeholder="Admin" readonly>
			{% else %}
			<input class="form-control" type="text" placeholder="Free" readonly>
			{% endif %}

		</form>
		<br>
		<a href="{% url 'profiles:delete_account'%}">Delete account</a>
	</div>
</div>
{% endblock %}