api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'
urlpatterns = [
    url(r'^(?P<dataset_id>[0-9]+)/(?P<field_name>[\w\-]+)$', views.get_field, name='get_field'),
]

build_model/urls.py
from django.conf.urls import url

from . import views

app_name = 'build_model'
urlpatterns = [
    url(r'^$', views.all, name='all'),
    url(r'^(?P<model_id>[0-9]+)/info$', views.info, name='info'),
    url(r'^(?P<dataset_id>[0-9]+)$', views.build, name="build"),
    url(r'^(?P<model_id>[0-9]+)/delete_model',
        views.delete_model, name='delete_model'),
    url(r'^(?P<model_id>[0-9]+)/test$', views.test, name='test'),
    url(r'^results/$', views.results, name='results'),
]

dataset/urls.py
from django.conf.urls import url

from . import views

app_name = 'dataset'
urlpatterns = [
    url(r'^$', views.upload, name='upload'),
    url(r'^(?P<dataset_id>[0-9]+)/delete_dataset', views.delete_dataset, name='delete_dataset'),
    url(r'^(?P<dataset_id>[0-9]+)/edit$', views.edit, name='edit'),
    url(r'^(?P<dataset_id>[0-9]+)/(?P<field_name>[\w\-]+)$', views.edit_field, name='edit_field'),
    url(r'^hide_field/$', views.hide_field, name='hide_field'),
]

profiles/urls.py
from django.conf.urls import url

from . import views

app_name = 'profiles'
urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^delete_account/$', views.delete_account, name='delete_account'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^info/$', views.user_profile, name='user_profile'),
]

build_model/models.py
from django.db import models
from dataset.models import Dataset
from django.contrib.auth.models import User


class DataModel(models.Model):
    name = models.CharField(max_length=30)
    params = models.TextField()
    dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE)
    file_model = models.BinaryField()
    metrics = models.TextField()
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Result(models.Model):
    data_model = models.ForeignKey(DataModel, on_delete=models.CASCADE)
    description = models.TextField(default='')
    pub_date = models.DateTimeField('date published')
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    choice = models.TextField(default='')

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    try:
        instance.profile.save()
    except AttributeError:
        profile = Profile.objects.create(user=instance)
        profile.save()

build_model/forms.py
from django import forms
import json


def get_form(data_desc, y_field):
    fields = json.loads(data_desc)
    file_handler = FieldHandler(fields, y_field)
    return type('DynaForm', (forms.Form,), file_handler.formfields)


class FieldHandler():
    formfields = {}

    def __init__(self, fields, y_field):
        for field in fields:
            if not field == y_field:
                options = self.get_options(fields[field])
                f = getattr(
                    self,
                    "create_field_for_" + fields[field]['type']
                )(fields[field], options)
                self.formfields[field] = f

    def get_options(self, field):
        options = {}
        options['help_text'] = field.get("help_text", None)
        options['required'] = bool(field.get("required", 1))
        return options

    def create_field_for_number(self, field, options):
        options['max_value'] = int(field.get("max_value", "999999999"))
        options['min_value'] = int(field.get("min_value", "0"))
        return forms.IntegerField(
            widget=forms.NumberInput(
                attrs={'class': 'form-control'}), **options)

    def create_field_for_select(self, field, options):
        options['choices'] = [(c, c) for c in field['choices']]
        return forms.ChoiceField(
            widget=forms.Select(
                attrs={'class': 'form-control'}), **options)

profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        max_length=254,
        help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

build_model/views.py
import os
import json
import ast
import pickle
import pandas as pd
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.utils import timezone
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import *
from .models import DataModel, Result
from dataset.models import Dataset, Field
from .forms import get_form
from .encoder import *



@login_required
def all(request):
    if request.user.is_superuser:
        models = DataModel.objects.all()
    else:
        models = DataModel.objects.filter(user=request.user)
    metrics = {}
    for model in models:
        metrics[model.id] = ast.literal_eval(model.metrics)
    return render(
        request,
        'build_model/all.html',
        {'models': models, 'metrics': metrics})


@login_required
def build(request, dataset_id):
    try:
        if not request.user.is_superuser:
            dataset = Dataset.objects.get(pk=dataset_id, user=request.user)
        else:
            dataset = Dataset.objects.get(pk=dataset_id)
    except Exception as e:
        return HttpResponseRedirect(reverse('dataset:upload'))

    if not Field.objects.filter(data_file_id=dataset_id, is_y=True).exists():
        return HttpResponseRedirect(reverse('dataset:edit', args=(dataset_id,)))

    if request.method == 'GET':

        # reading CSV file
        data = pd.read_csv(dataset.file.url)

        encoded = make_encoder(data)
        if not dataset.label_encode:
            dataset.label_encode = pickle.dumps(encoded)
            dataset.save()
            # label_encode.close()

        # move encoder part in dataset signals
        encode(encoded, data)
        y_name = Dataset.objects.get(pk=dataset_id).get_y_name()
        X_names = Dataset.objects.get(pk=dataset_id).get_x_names()
        y = data[y_name]
        X = data[X_names]
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.8, random_state=241)

        clf = LogisticRegression(random_state=0, solver='lbfgs', multi_class='multinomial')
        models = [clf]
        for model in models:
            model.fit(X_train, y_train)
            y_pred = model.predict(X_test)

            # вычисляем метрики качества
            metrics = {}
            metrics["model_accuracy"] = round(accuracy_score(y_test, y_pred), 2)
            metrics["model_precision"] = round(precision_score(y_test, y_pred), 2)
            metrics["model_recall"] = round(recall_score(y_test, y_pred), 2)
            metrics["model_f1"] = round(f1_score(y_test, y_pred), 2)

            fid = pickle.dumps(model)
            params = json.dumps(model.get_params())
            try:
                DataModel(
                    file_model=fid,
                    dataset=dataset,
                    params=params,
                    metrics=metrics,
                    user=request.user).save()
            except Exception as e:
                print(e)
            # fid.close
        return HttpResponseRedirect(reverse('build_model:all'))


@login_required
def delete_model(request, model_id):
    try:
        if not request.user.is_superuser:
            model = DataModel.objects.get(pk=model_id, user=request.user)
        else:
            model = DataModel.objects.get(pk=model_id)
    except Exception:
        return HttpResponseRedirect(reverse('build_model:all'))
    model.delete()
    return HttpResponseRedirect(reverse('build_model:all'))


@login_required
def info(request, model_id):
    try:
        if not request.user.is_superuser:
            model = DataModel.objects.get(pk=model_id, user=request.user)
        else:
            model = DataModel.objects.get(pk=model_id)
    except Exception:
        return HttpResponseRedirect(reverse('build_model:all'))
    metrics = {}
    metrics[model.id] = ast.literal_eval(model.metrics)
    return render(
        request,
        'build_model/info.html',
        {'model': model, 'metrics': metrics})


# Представление, которое строит форму
@login_required
def test(request, model_id):
    try:
        if not request.user.is_superuser:
            model = DataModel.objects.get(pk=model_id, user=request.user)
        else:
            model = DataModel.objects.get(pk=model_id)
    except Exception:
        return HttpResponseRedirect(reverse('build_model:all'))
    if model:
        dataset = Dataset.objects.get(pk=model.dataset_id)
        form_class = get_form(
            dataset.description,
            dataset.get_y_name())
        if request.method == 'POST':
            form = form_class(request.POST)
            if form.is_valid():
                data = {}
                for field, value in form.cleaned_data.items():
                    data[field] = [value]
                user_data = pd.DataFrame(data)
                # загружаем файл с кодированными значениями
                encoded_labels = pickle.loads(dataset.label_encode)
                file_model = pickle.loads(model.file_model)
                encode(encoded_labels, user_data)
                y_name = dataset.get_y_name()
                answer = file_model.predict(user_data)

                result = Result(data_model=model, description=json.dumps(data), user=request.user, pub_date=timezone.now(), choice=answer)
                result.save()

                return render(
                    request,
                    "build_model/answ.html",
                    {'answ': answer, 'description': result.description})
        else:
            form = form_class()
        return render(request, "build_model/profile.html", {'form': form, })
    else:
        return render(request, "build_model/profile.html")


@login_required
def results(request):
    if request.user.is_superuser:
        results = Result.objects.all()
    else:
        results = Result.objects.filter(user=request.user)

    for result in Result.objects.all():
        result.description = (json.loads(result.description))
    return render(request, "build_model/results.html", {'results': results})

profiles/views.py
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from .forms import SignUpForm
from .tokens import account_activation_token

from django.contrib.auth.models import User
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth import login, logout, authenticate

from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth.decorators import login_required

import os

from django.contrib.auth.forms import AuthenticationForm


@login_required
def user_profile(request):
    user = User.objects.get(id=request.user.id)
    if request.method == 'GET':
        return render(
            request,
            'profiles/user_profile.html',
            {'user': user, }, )
    elif request.method == 'POST':
        user.username  = request.POST['userName']
        user.email = request.POST['userEmail']
        user.save()
        return HttpResponseRedirect(reverse('profiles:user_profile'))


@login_required
def delete_account(request):
    user = User.objects.get(id=request.user.id)
    user.delete()
    return HttpResponseRedirect(reverse('profiles:signup'))

@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('profiles:signin'))


def account_activation_sent(request):
    return render(request, 'profiles/account_activation_sent.html')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        #login(request, user)
        return HttpResponseRedirect(reverse('profiles:signin'))
    else:
        return render(request, 'account_activation_invalid.html')


def signup(request):
    if request.method == 'POST':
        if request.user.is_active:
            logout(request)
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate Your MySite Account'
            message = render_to_string('profiles/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': force_text(urlsafe_base64_encode(force_bytes(user.pk))),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)

            dir = os.path.dirname(__file__)
            log_file = os.path.join(dir, '../logs/tokens.log')
            with open(log_file, 'a') as the_file:
                the_file.write(message)

            return HttpResponseRedirect(reverse('profiles:account_activation_sent'))
    else:
        form = SignUpForm()
    return render(request, 'profiles/register.html', {'form': form})


def signin(request):
    if request.method == 'GET':
        if request.user.is_active:
            return HttpResponseRedirect(reverse('dataset:upload'))
        else:
            form = AuthenticationForm()
            return render(request,'profiles/signin.html', {'form': form} )
    elif request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('dataset:upload'))
        else:
            form.add_error(None, "Wrong")
            return render(request,'profiles/signin.html', {'form': form} )

build_model/templates/build_model/all.html
{% extends "base.html" %}
{% load dict_key_access %}

{% block content %}
<h2>Models</h2>
<br>
{%if models %}
<div class="table-responsive">
	<table class="table table-bordered">
		<tr>
		<th>name</th>
		<th>quality</th>
		<th></th>
		</tr>
		{% for model in models %}
		<tr>
			<td>
				<a href="{% url 'dataset:edit' model.dataset_id %}">{{model.dataset}}</a>
			<td>
				<p>{{model.algoritm}}</p>
		        <p> accuracy: {{ metrics|get_item:model.id|get_item:"model_accuracy" }} </p>
		        <p> precision:{{ metrics|get_item:model.id|get_item:"model_precision" }} </p>
		        <p> recall:   {{ metrics|get_item:model.id|get_item:"model_recall" }} </p>
		        <p> f1:		  {{ metrics|get_item:model.id|get_item:"model_f1" }} </p>
			</td>
			<td>
				<a href="{% url 'build_model:info' model.id %}"><i class="fa fa-fw fa-gear"></i>Parameters</a>
				<a href="{% url 'build_model:test' model.id %}"><i class="fa fa-fw fa-tasks"></i>Test</a>
				<a href="{% url 'build_model:delete_model' model.id %}"><i class="fa fa-fw fa-trash"></i>Delete</a>
			</td>
		</tr>
		{% endfor %}
	</table>
</div>
{% else %}
<p>There isn't models.</p>
<a href="{% url 'dataset:upload' %}">Build new model</a>
{% endif%}
{% endblock content %}

build_model/templates/build_model/answ.html
{% extends "base.html" %}

{% block content %}
<center><h2>Testing model</h2></center>
<br>

<div class="card mx-auto w-50">
	<div class="card-body">	
		<br>
		your result is {{answ}}
	</div>
</div>
<br>
<br>
{% endblock content %}

build_model/templates/build_model/build.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h2>Build model</h2>

<div class="divider"></div>

<form id="form" enctype="multipart/form-data" method="post">
  {% csrf_token %}
  <div class="form-group" id="classifier-input">
	{% if classifiers %}
	<select class="custom-select mr-sm-2" name="classifier_name" id="inlineFormCustomSelect">
	    {% for classifier in classifiers %}
		    <option value="{{classifier.name}}">{{classifier.name}}</option>	    
		{% endfor %}
	</select>
	{% endif %}
  <div class="divider"></div>
  </div>

  <button type="submit" style="visibility: hidden;" class="btn btn-primary" id="submit-button">Build model</button>
</form>
<div class="divider"></div>

{% endblock content %}
{% block javascript %}
{{ block.super }}
<script src="{% static "js/build.js" %}"></script>
{% endblock %}

build_model/templates/build_model/info.html
{% extends "base.html" %}
{% load dict_key_access %}

{% block content %}
<h2>Models</h2>
<br>

{%if model %}
<div class="table-responsive">
	<table class="table table-bordered">
		<tr>
		<th>name</th>
		<th>params</th>
		</tr>
		<tr>
			<td>
				<a href="{% url 'dataset:edit' model.dataset_id %}">{{model.dataset}}</a>
			</td>
			<td>{{model.params}}</td>
		</tr>
	</table>
</div>
{% else %}
<p>There isn't models.</p>
<a href="{% url 'dataset:upload' %}">Build new model</a>
{% endif%}
{% endblock content %}

build_model/templates/build_model/profile.html
{% extends "base.html" %}

{% block content %}
<center><h2>Testing model</h2></center>
<br>
<div class="card mx-auto w-50">
	<div class="card-body">	
	{% if form %}
		<form enctype="multipart/form-data" method="post" role="form">
			{% csrf_token %}
				{% for field in form %}
				<div class="form-group row">
					{{ field.label_tag }}
					{{ field }}
					<small id="passwordHelpBlock" class="form-text text-muted">
						{{ field.help_text }}
					</small>
				</div>
				{% endfor %}		
			<button type="submit" class="btn btn-block btn-primary">Upload</button>
		</form>
	{% else %}
	<p>There isn't models.</p>
	<a href="{% url 'dataset:upload' %}">Build new model</a>
	{% endif%}
	</div>
</div>
<br>
<br>
{% endblock content %}

build_model/templates/build_model/results.html
{% extends "base.html" %}

{% block content %}
<table class="table table-bordered">
		<tr>
		<th>date</th>
		<th>desc</th>
		<th>result</th>
		</tr>
{% for result in results %}
	<tr>
		<td>{{result.pub_date}}</td>
		<td>{{result.description}}</td>
		<td>{{result.choice}}</td>
	</tr>
{% endfor%}
</table>
{% endblock%}