api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'
urlpatterns = [
    url(r'^(?P<dataset_id>[0-9]+)/(?P<field_name>[\w\-]+)$', views.get_field, name='get_field'),
]

build_model/urls.py
from django.conf.urls import url

from . import views

app_name = 'build_model'
urlpatterns = [
    url(r'^$', views.all, name='all'),
    url(r'^(?P<model_id>[0-9]+)/info$', views.info, name='info'),
    url(r'^(?P<dataset_id>[0-9]+)$', views.build, name="build"),
    url(r'^(?P<model_id>[0-9]+)/delete_model',
        views.delete_model, name='delete_model'),
    url(r'^(?P<model_id>[0-9]+)/test$', views.test, name='test'),
    url(r'^results/$', views.results, name='results'),
]

dataset/urls.py
from django.conf.urls import url

from . import views

app_name = 'dataset'
urlpatterns = [
    url(r'^$', views.upload, name='upload'),
    url(r'^(?P<dataset_id>[0-9]+)/delete_dataset', views.delete_dataset, name='delete_dataset'),
    url(r'^(?P<dataset_id>[0-9]+)/edit$', views.edit, name='edit'),
    url(r'^(?P<dataset_id>[0-9]+)/(?P<field_name>[\w\-]+)$', views.edit_field, name='edit_field'),
    url(r'^hide_field/$', views.hide_field, name='hide_field'),
]

profiles/urls.py
from django.conf.urls import url

from . import views

app_name = 'profiles'
urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^delete_account/$', views.delete_account, name='delete_account'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^info/$', views.user_profile, name='user_profile'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}Scoring app{% endblock %}</title>
    {% block stylesheets %}
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Load background image -->
    <link href="{% static "css/back.css" %}" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="{% static "css/sb-admin.css" %}" rel="stylesheet">
    <!-- my own css styles -->
    <link href="{% static "css/my.css" %}" rel="stylesheet">
    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Chartjs-->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js'></script>
    {% endblock %}
  </head>

  <body class="fixed-nav bg-dark" id="page-top">
    {% block page %}
    
    {% block navigation %}
    {% include "navigation.html" %}
    {% endblock %}
    
    {% block main %}  
    <!-- Content HERE !!! -->
    <div class="content-wrapper bg-light">
      <div class="container-fluid">
        <div class="container">
        {% block content %}{% endblock %}
        </div>
      </div>
    </div>
    {% endblock %}
    
    {% block javascript %}
    <!-- Bootstrap core JavaScript-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- navbar toogle -->
    <script src="{% static "js/sb-admin.min.js" %}"></script>
    {% endblock %}
    {% endblock %}
  </body>
</html>

templates/head.html
{% load static %}

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <img src="{% static "img/logo.png" %}">
    <div class="divider"></div>
    {% if user.is_authenticated %}
    <a class="navbar-brand" href="/dataset">Scoring app</a>
    {% else %}
    <a class="navbar-brand" href="/">Scoring app</a>
    {% endif%}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        {% include 'user.html'%}
      </ul>
    </div>
  </div>
</nav>

templates/index.html
{% extends "base.html" %}

{% block navigation%}
	{% include 'head.html' %}
{% endblock %}

{% block main %}
<!-- Page Content -->
<div class="row">
	<div class="col-lg-12 text-center">
	  <h1 class="mt-5">Simple web-app for running sklearn models</h1>
	  <p class="lead">Complete with pre-defined file paths and responsive navigation!</p>
	</div>
</div>

{% endblock %}

templates/navigation.html
{% load static %}
<!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <img src="{% static "img/logo.png" %}">
    <div class="divider"></div>
    <a class="navbar-brand" href="/">Scoring app</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarResponsive">
	  <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
	    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Datasets">
	      <a class="nav-link" href="{% url 'dataset:upload' %}">
	        <i class="fa fa-fw fa-file"></i>
	        <span class="nav-link-text">Dataset</span>
	      </a>
	    </li>

	    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Models">
	      <a class="nav-link" href="{% url 'build_model:all' %}">
	        <i class="fa fa-fw fa-area-chart"></i>
	        <span class="nav-link-text">Models</span>
	      </a>
	    </li>
	    
	    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Results">
	      <a class="nav-link" href="{% url 'build_model:results' %}">
	        <i class="fa fa-fw fa-flag-checkered"></i>
	        <span class="nav-link-text">Results</span>
	      </a>
	    </li>

	    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Settings">
	      <a class="nav-link" href="{% url 'profiles:user_profile' %}">
	        <i class="fa fa-fw fa-gear"></i>
	        <span class="nav-link-text">Settings</span>
	      </a>
	    </li>
		
		<li class="nav-item" data-toggle="tooltip" data-placement="right" title="About">
	      <a class="nav-link" href="">
	        <i class="fa fa-fw fa-info-circle"></i>
	        <span class="nav-link-text">About</span>
	      </a>
	    </li>

	  </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% include 'user.html' %}
      </ul>
    </div>
  </nav>

templates/user.html
{% if user.is_authenticated %}
<div class="dropdown">
  <a class="nav-link" data-toggle="dropdown" href="#"><i class="fa fa-fw fa-user-circle"></i> {{ user.get_username }}</a>
  <ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="dropdownMenu1">
    <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'profiles:user_profile' %}"><i class="fa fa-fw fa-cog"></i> settings</a></li>
    <li role="presentation" class="divider"></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'profiles:logout'%}"><i class="fa fa-fw fa-sign-out"></i> logout</a></li>
  </ul>
</div>
{% else %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'profiles:signin' %}">Sign in</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'profiles:signup' %}">Sign up</a>
  </li> 
{% endif %}